### ISSUE TITLE
NPR 

### ISSUE THREAD

**Issue by yujiaao** [yujiaao/ictclas4j#1]
java.lang.NullPointerException
at org.ictclas4j.bean.Dictionary.getMaxMatch(Dictionary.java:618)
at org.ictclas4j.segment.GraphGenerate.generate(GraphGenerate.java:93)
at org.ictclas4j.segment.SegTag.split(SegTag.java:96)
at org.languagetool.tokenizers.zh.ChineseWordTokenizer.tokenize(ChineseWordTokenizer.java:65)
at com.kennycason.kumo.nlp.tokenizers.LanguageToolTokenizer.tokenize(LanguageToolTokenizer.java:20)
at com.kennycason.kumo.nlp.tokenizers.ChineseWordTokenizer.tokenize(ChineseWordTokenizer.java:13)

**Comment by yujiaao** [comment]
Simple Text to trigger the bug：

日本早在1923年的关东大地震后就着手制定校舍安全政策，1995年阪神大地震后开始实施“校舍补强计划”，对不具备抗御7级地震的校舍进行加固，2008年中国汶川地震后，日本政府迅速启动了面向45万所公立中小学的“五年补强计划”。

**Comment by yujiaao** [comment]
Patch to fix: 

Index: src/main/java/org/ictclas4j/segment/GraphGenerate.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/org/ictclas4j/segment/GraphGenerate.java	(revision 1cae483dfc028b3fd8e5d04e2428278821b437fa)
+++ src/main/java/org/ictclas4j/segment/GraphGenerate.java	(revision )
@@ -136,7 +136,9 @@
 	/**
 	 * 生成二叉图表,每个节点表示相邻两个词组的耦合关系,如:说@的确
 	 * 
-	 * @param sgs
+	 * @param seg
+	 * @param biDict
+	 * @param dict
 	 */
 	public static SegGraph biGenerate(SegGraph seg,Dictionary dict,Dictionary biDict) {
 		SegGraph segGraph = null;
Index: README.md
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- README.md	(revision )
+++ README.md	(revision )
@@ -0,0 +1,32 @@
+
+# ICTCLAS4J 中文分词系统使用说明
+
+1. ictclas4j 是在中科院开源分词系统 FreeICTCLAS  的基础上重新实现和改进而来
+2. 任何人不得将此用于商业用途，仅限个人学习研究之用
+3. 该分词程序的最终解释权张新波（sinboy）和中科院张华平所有
+4. 对使用中遇到的问题，请到 ictclas  论坛组内交流
+5. 也可直接 Email 给我：sinboy@126.com
+
+ICTCLAS4J 大事记  
+
+2007-06-04
+     
+   FreeICTCLAS 中文分词系统从 2006 年 3 月就开始接触，之后通过研读相关论文和源代码，写了一系列的学习笔记 ，给很多同样的中文分词爱好者提供了一个可参考的文档资料 。但因为工作及其它原因（嘿嘿，说白就了就是比较偷懒 ，没有坚持下去），把该项目做成一个 java 版的原始想法一度中断 。之后，也曾多次尝试重新拾起，完成我的一个心愿 ，但复杂的工作都让我半途而费。
+   
+   4 月份的时候，一个爱好才 MSN 上问我相关问题 ，又激起了我的原始想法，同时看到吕震宇老师只用了半个月的时间就完成了 C＃版本的工作，
+   并且写了完成的系列文章，又大大刺激我的神 经。想想我的系列文章只到半道，ictclas4j 的程序也是半拉 子工程，真是惭愧之极。于是下定决定，一定要把这个项目完成 ，给自己也给关心 ictclas 的朋友一个交待。        经过三个星期的不懈努力，到现在为止，基本上完整的实现了原 Fre eICTCLAS 所实现的功能。原 VC＋＋实现的程序比我想象的更 复杂，中间涉及大量的临时性的数据结构和大量的全局变量 ，搞的我非常头大，好几次都有放弃的想法。不过谢天谢地 ，我这次终于坚持下来了。
+   
+   从java 程序的角度从出 ，我对原来的数据结构做了大量调整和优化，去掉了很多不必要的中间 变量。经过优化后，在整个分词过后中只用到两个对象：Atom 、SegNode，原子和分词结点，整个分词过程就是对 SegNo de 的不断调整和改进，最终得到分词结果。
+   
+   因为到现在为止，我只是做了一些简单的测试，可能还有很多的 BUG 在里面（对标点符号的处理就是一问题），并且分词的速度还远远达不 到我的要求，程序还有很多改进的地方，所以暂时源代码还不会放上来 ，但我想最迟一个星期之内，我可以上传到论坛供大家测试。同时 ，
+
+我已在 Google Code 上申请了 ictclas4j 的开源项目，期望有兴趣的朋友加入进来共同改进。
+      
+   附近中的文件是 ictclas4j 程序在分词过程输出的完整分词步 骤记录，对大家直观理解该分词原是应该是一个有益的帮助 。这个想法也得益于吕震宇的 SharpICTCLAS ，在此表示感谢！同时感谢 DanceFire 的几篇精辟入理的分析 文章，给了我很大的帮助。 　
+   
+   
+2019-03-01
+
+   NPE fix   
+   
+   
\ No newline at end of file
Index: src/test/java/org/ictclas4j/bean/DictionaryTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/test/java/org/ictclas4j/bean/DictionaryTest.java	(revision )
+++ src/test/java/org/ictclas4j/bean/DictionaryTest.java	(revision )
@@ -0,0 +1,16 @@
+package org.ictclas4j.bean;
+
+import org.junit.Test;
+
+import static org.junit.Assert.*;
+
+public class DictionaryTest {
+    @Test
+    public void getMaxMatch() throws Exception {
+        Dictionary dict = new Dictionary();
+
+
+        dict.getMaxMatch("始##始");
+    }
+
+}
\ No newline at end of file
Index: src/test/java/org/ictclas4j/segment/GraphGenerateTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/test/java/org/ictclas4j/segment/GraphGenerateTest.java	(revision )
+++ src/test/java/org/ictclas4j/segment/GraphGenerateTest.java	(revision )
@@ -0,0 +1,14 @@
+package org.ictclas4j.segment;
+
+import org.junit.Test;
+
+import static org.junit.Assert.*;
+
+public class GraphGenerateTest {
+    @Test
+    public void generate() throws Exception {
+       // GraphGenerate.generate()
+
+    }
+
+}
\ No newline at end of file
Index: src/test/java/org/ictclas4j/segment/SegTagTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/test/java/org/ictclas4j/segment/SegTagTest.java	(revision 1cae483dfc028b3fd8e5d04e2428278821b437fa)
+++ src/test/java/org/ictclas4j/segment/SegTagTest.java	(revision )
@@ -3,11 +3,21 @@
 import java.io.FileInputStream;
 import java.io.InputStream;
 
+import org.ictclas4j.bean.SegResult;
 import org.junit.Test;
 
+import static org.junit.Assert.assertTrue;
+
 public class SegTagTest
 {
-	/**
+    @Test
+    public void split() throws Exception {
+		String src = "日本早在1923年的关东大地震后就着手制定校舍安全政策，1995年阪神大地震后开始实施“校舍补强计划”，对不具备抗御7级地震的校舍进行加固，2008年中国汶川地震后，日本政府迅速启动了面向45万所公立中小学的“五年补强计划”。";
+		SegResult res = new SegTag(1).split(src);
+		assertTrue(res.getMrList().size()>0);
+    }
+
+    /**
 	 * Tokenizing this text causes an endless loop: 月份牌
 	 * @see <a href="http://code.google.com/p/ictclas4j/issues/detail?id=13">Issue 13</a>
 	 */
Index: src/main/java/org/ictclas4j/bean/Dictionary.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/org/ictclas4j/bean/Dictionary.java	(revision 1cae483dfc028b3fd8e5d04e2428278821b437fa)
+++ src/main/java/org/ictclas4j/bean/Dictionary.java	(revision )
@@ -507,6 +507,8 @@
   protected int findInModifyTable(int index, String res, int handle) {
     int result = -1;
 
+    if(index<0) return result;
+
     if (mts != null && mts.size() > index) {
       ArrayList<WordItem> wis = mts.get(index).getWords();
       if (res != null && wis != null) {
@@ -614,7 +616,7 @@
         int found = findInOriginalTable(pw.getIndex(), pw.getRes(), -1);
         if (found == -1) {
           ArrayList<WordItem> wis = wts.get(pw.getIndex()).getWords();
-          
+          if(wis!=null)
           for (int j = 0; j < wis.size(); j++) {
             int compValue = GFString.compareTo(wis.get(j).getWord(), pw.getRes());
             if (compValue == 1) {
Index: pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- pom.xml	(revision 1cae483dfc028b3fd8e5d04e2428278821b437fa)
+++ pom.xml	(revision )
@@ -1,10 +1,12 @@
 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
 	<modelVersion>4.0.0</modelVersion>
+	
 	<groupId>com.googlecode.ictclas4j</groupId>
 	<artifactId>ictclas4j</artifactId>
 	<version>1.1.0-SNAPSHOT</version>
@@ -40,11 +42,23 @@
 		<developer>
 			<name>Ying Jiang</name>
 		</developer>
+		<developer>
+			<name>Wanxiang Xing</name>
+		</developer>
 	</developers>
-	<url>http://code.google.com/p/ictclas4j/</url>
+	<url>https://github.com/yujiaao/ictclas4j</url>
 	<scm>
-		<url>http://code.google.com/p/ictclas4j/source/browse/</url>
-		<connection>scm:svn:http://ictclas4j.googlecode.com/svn/trunk/</connection>
-		<developerConnection>scm:svn:https://ictclas4j.googlecode.com/svn/trunk/</developerConnection>
+		<url>https://github.com/yujiaao/ictclas4j</url>
+		<connection>scm:git:https://github.com/yujiaao/ictclas4j</connection>
+		<developerConnection>scm:git:https://github.com/yujiaao/ictclas4j</developerConnection>
 	</scm>
+
+	<distributionManagement>
+		<repository>
+			<id>sslldev</id>
+			<name>Qsn.so Internal Repository</name>
+			<url>http://dev.issll.com/artifactory/libs-snapshot-local</url>
+		</repository>
+	</distributionManagement>
+
 </project>
\ No newline at end of file
